import Foundation

public protocol LLMProvider: Sendable {
    var id: String { get }
    var displayName: String { get }

    func availability() async -> ProviderAvailability

    /// Streams one round of a chat completion. Pass `tools` to advertise the
    /// callable functions to the model — providers that don't support tool
    /// calling can ignore them. The returned stream emits `.textDelta` for
    /// each chunk of generated text and `.toolCall` whenever the model
    /// finalises a tool invocation (id, name, arguments JSON).
    func chat(
        messages: [ChatMessage],
        tools: [ToolSpec]
    ) -> AsyncThrowingStream<StreamEvent, Error>
}

public enum ProviderAvailability: Equatable {
    case ready
    case unavailable(reason: String)
}

/// Events the streaming chat can produce. Text and tool calls are
/// interleaved according to what the model emits. Each `.toolCall` is
/// atomic — providers buffer the arguments internally and emit only when
/// fully assembled, so callers don't have to parse partial JSON.
public enum StreamEvent: Sendable, Hashable {
    case textDelta(String)
    /// `thoughtSignature` is a Gemini-2.5+ opaque base64 blob that must be
    /// echoed back alongside the matching part. Other providers leave it nil.
    case toolCall(id: String, name: String, argumentsJSON: String, thoughtSignature: String? = nil)
    /// Chain-of-thought emitted by "thinking" models (DeepSeek v4, etc.).
    /// Stored on the assistant message so the next round can round-trip it
    /// to the provider that emitted it. ChatSession does not display it.
    case reasoningDelta(String)
    /// An image generated by the model (e.g. Gemini image models return it
    /// inline as base64). ChatSession persists it as an attachment on the
    /// assistant message.
    case imageOutput(data: Data, mimeType: String)
    /// Performance metrics for the turn, emitted once when the stream ends.
    /// Providers that can't measure anything never emit it.
    case metrics(GenerationMetrics)
}

/// Performance metrics for one assistant turn. Every field is optional —
/// each backend fills what it can measure or report. OpenAI-compatible
/// servers (vLLM, NIM, LM Studio, llama.cpp…) report token counts via the
/// `usage` block; durations are measured client-side from the byte stream.
/// Other backends (Apple Intelligence) may leave most fields nil. Stored on
/// the assistant `Message` for display and persistence; never sent to the LLM.
public struct GenerationMetrics: Sendable, Hashable, Codable {
    /// Input tokens, as reported by the server's usage block.
    public var promptTokens: Int? = nil
    /// Output tokens generated, as reported by the server's usage block.
    public var completionTokens: Int? = nil
    /// Seconds from request sent to the first token received (client-measured).
    public var timeToFirstToken: TimeInterval? = nil
    /// Seconds from the first token to the last — the decode window,
    /// excluding the initial latency captured by `timeToFirstToken`.
    public var generationDuration: TimeInterval? = nil
    /// Seconds spent processing the prompt (prefill), as reported by the
    /// server. Ollama provides it; OpenAI-compatible servers don't, so it
    /// stays nil there.
    public var promptDuration: TimeInterval? = nil

    /// Decode throughput: output tokens over the generation window. nil
    /// unless both are known and the window is positive. Derived, so never
    /// drifts from the raw measurements.
    public var tokensPerSecond: Double? {
        guard let completionTokens, let generationDuration, generationDuration > 0 else { return nil }
        return Double(completionTokens) / generationDuration
    }

    /// Prefill throughput: prompt tokens over the prompt-processing window.
    /// nil unless both are known and the window is positive.
    public var promptTokensPerSecond: Double? {
        guard let promptTokens, let promptDuration, promptDuration > 0 else { return nil }
        return Double(promptTokens) / promptDuration
    }
}

public struct ChatMessage: Hashable, Sendable {
    public enum Role: String, Hashable, Sendable {
        case system
        case user
        case assistant
        case toolCall
        case toolResult
    }

    public let role: Role
    public let content: String
    /// Local file URLs of image attachments on a `.user` message. Only
    /// multimodal providers (MLX VLM today) consume them; text providers
    /// ignore them.
    public let imageURLs: [URL]
    public let toolCallID: String?
    public let toolName: String?
    public let toolIsError: Bool?
    public let reasoningContent: String?
    public let thoughtSignature: String?

    public nonisolated init(
        role: Role,
        content: String,
        imageURLs: [URL] = [],
        toolCallID: String? = nil,
        toolName: String? = nil,
        toolIsError: Bool? = nil,
        reasoningContent: String? = nil,
        thoughtSignature: String? = nil
    ) {
        self.role = role
        self.content = content
        self.imageURLs = imageURLs
        self.toolCallID = toolCallID
        self.toolName = toolName
        self.toolIsError = toolIsError
        self.reasoningContent = reasoningContent
        self.thoughtSignature = thoughtSignature
    }
}

/// Wraps a legacy text-only `AsyncThrowingStream<String, Error>` into the
/// new event stream by emitting each delta as `.textDelta`. Used by all
/// providers until tool emission is wired per-provider in Bloc 4.
public func wrapAsTextStream(_ source: AsyncThrowingStream<String, Error>) -> AsyncThrowingStream<StreamEvent, Error> {
    AsyncThrowingStream { continuation in
        let task = Task {
            do {
                for try await delta in source {
                    if Task.isCancelled { break }
                    continuation.yield(.textDelta(delta))
                }
                continuation.finish()
            } catch {
                continuation.finish(throwing: error)
            }
        }
        continuation.onTermination = { _ in task.cancel() }
    }
}

/// Drops tool-related entries from the history when targeting a provider
/// that doesn't yet know how to serialise them. Temporary helper for Bloc 3;
/// Bloc 4 replaces each provider's mapping with proper tool round-trip.
public func dropToolMessages(_ messages: [ChatMessage]) -> [ChatMessage] {
    messages.filter { $0.role == .user || $0.role == .assistant || $0.role == .system }
}
